TimViec/Models/Job.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TimViec.Models
{
    public class Job
    {
        public int Id { get; set; }

        [Required, StringLength(100)]
        public string Title { get; set; }

        public int CompanyID { get; set; }
        public Company? Company { get; set; }

        [Required]
        public string Location { get; set; }
        [Required]
        public int Salary { get; set; }

        [Required]
        public string Description { get; set; }

        public int? SkillID { get; set; }

        public Skill? Skill { get; set; }

        public int? RankID { get; set; }

        public Rank? Rank { get; set; }

        [Required]
        public string img {  get; set; }

        public string? R1_Language { get; set; }

        public string? R2_Language { get; set; }

        public string? R3_Language { get; set; }

		[ForeignKey("Type_work")]
		public int? Type_workID { get; set; }

        public Type_work? Type_work { get; set; }
        [Required]
        public string Work_responsibility {  get; set; }
        [Required]
        public string treatment { get; set; }

        public string? advanced_skill { get; set; }
    }
}

TimViec/Controllers/JobController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TimViec.Models;
using TimViec.Repository;
using TimViec.Respository;
using TimViec.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace TimViec.Controllers
{
	[Authorize]
	[Authorize(Roles = "User")]
	public class JobController : Controller
	{
		private readonly IJobRespository _jobRepository;
		private readonly ICompanyRespository _companyRepository;
		private readonly IStatusRepository _statusRepository;
		private readonly IRankRespository _rankRespository;
		private readonly ISkillRespository _skillRespository;
		private readonly IType_WorkRespository _WorkRespository;
		private readonly ICityRespository _cityRespository;
		private readonly IfavouriteJob _favouriteJob;
		private readonly IfeedbackRepository _feedbackRepository;
		private readonly UserManager<ApplicationUser> _userManager;

		public JobController(ICompanyRespository companyRepository,
			IJobRespository jobRepository,
			IStatusRepository statusRepository,
			IRankRespository rankRespository,
			ISkillRespository skillRespository,
			IType_WorkRespository type_workRespository,
			ICityRespository cityRespository,
			IfavouriteJob favouriteJob,
			IfeedbackRepository feedback,
			UserManager<ApplicationUser> userManager)
		{
			_jobRepository = jobRepository;
			_companyRepository = companyRepository;
			_statusRepository = statusRepository;
			_userManager = userManager;
			_skillRespository = skillRespository;
			_WorkRespository = type_workRespository;
			_cityRespository = cityRespository;
			_rankRespository = rankRespository;
			_favouriteJob = favouriteJob;
			_feedbackRepository = feedback;
		}

		private async Task DisplayDropdown()
		{
			var rank = await _rankRespository.GetAllAsync();
			var skill = await _skillRespository.GetAllAsync();
			var type_work = await _WorkRespository.GetAllAsync();
			var city = await _cityRespository.GetAllAsync();

			ViewBag.Skill = skill.ToList();
			ViewBag.Type = type_work.ToList();
			ViewBag.Rank = rank.ToList();
			ViewBag.Location = city.ToList();
		}

		//all Job                                 
		public async Task<IActionResult> Job()
		{
			await DisplayDropdown();

			var job = await _jobRepository.GetAllAsync();
			return View(job);
		}

		//details job     
		public async Task<IActionResult> Details_Job(int id)
		{
			await DisplayDropdown();

			var job = _jobRepository.Details_Job(id);
			if (job == null)
			{
				return NotFound();
			}
			return View(job);
		}
		public async Task<IActionResult> GetAllFavouriteJob()
		{
			await DisplayDropdown();
			var getemailuser = await _userManager.GetUserAsync(User);

			var fbJob = await _favouriteJob.GetAllAsync();
			var display = fbJob.Where(e => e.email == getemailuser.Email);
			return View(display);
		}

		[HttpGet]
		public async Task<IActionResult> Favourite_Job(favourite_job favourite_Job, int ID)
		{
			var getemailuser = await _userManager.GetUserAsync(User);
			await DisplayDropdown();
			var getfvrjob = await _favouriteJob.GetAllAsync();

			var getID = await _jobRepository.GetByIdAsync(ID);
			favourite_Job.email = getemailuser.Email;
			favourite_Job.Id = 0;
			favourite_Job.IDJob = getID.Id;
			favourite_Job.Name = getID.Title;
			favourite_Job.R1_Language = getID.R1_Language;
			favourite_Job.R2_Language = getID.R2_Language;
			favourite_Job.R3_Language = getID.R3_Language;
			favourite_Job.image = getID.img;
			favourite_Job.favourite = (int)Constants.favouriteJob.favourite;

			await _favouriteJob.AddAsync(favourite_Job);
			return RedirectToAction("GetAllFavouriteJob"); ;
		}

		[HttpGet]
		public async Task<IActionResult> ChangeFavourite_Job(favourite_job favourite_Job, int ID)
		{
			await DisplayDropdown();
			await _favouriteJob.DeleteAsync(ID);
			return RedirectToAction("GetAllFavouriteJob"); ;
		}
	}
}

TimViec/Controllers/StatusJobController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TimViec.Helpers;
using TimViec.Models;
using TimViec.Repository;
using TimViec.Respository;

namespace TimViec.Controllers
{
    [Authorize]
    [Authorize(Roles = "User")]
    public class StatusJobController : Controller
    {
        private readonly IJobRespository _jobRepository;
        private readonly ICompanyRespository _companyRepository;
        private readonly IStatusRepository _statusRepository;
        private readonly IRankRespository _rankRespository;
        private readonly ISkillRespository _skillRespository;
        private readonly IType_WorkRespository _WorkRespository;
        private readonly ICityRespository _cityRespository;
		private readonly UserManager<ApplicationUser> _userManager;

		public StatusJobController(ICompanyRespository companyRepository,
            IJobRespository jobRepository,
            IStatusRepository statusRepository,
            IRankRespository rankRespository,
            ISkillRespository skillRespository,
            IType_WorkRespository type_workRespository,
            ICityRespository cityRespository,
            UserManager<ApplicationUser> userManager)
        {
            _jobRepository = jobRepository;
            _companyRepository = companyRepository;
            _statusRepository = statusRepository;
            _skillRespository = skillRespository;
            _WorkRespository = type_workRespository;
            _cityRespository = cityRespository;
			_userManager = userManager;
			_rankRespository = rankRespository;
        }

        private async Task DisplayDropdown()
        {
            var rank = await _rankRespository.GetAllAsync();
            var skill = await _skillRespository.GetAllAsync();
            var type_work = await _WorkRespository.GetAllAsync();
            var city = await _cityRespository.GetAllAsync();

            ViewBag.Skill = skill.ToList();
            ViewBag.Type = type_work.ToList();
            ViewBag.Rank = rank.ToList();
            ViewBag.Location = city.ToList();
        }

        //status job
        public IActionResult StatusJob()
        {

            var name = User.Identity.Name;
            var status = _statusRepository.GetListJobByEmail(email: name);

            foreach (var job in status)
            {
                job.StatusName = EnumExtension.GetEnumDescription((Constants.StatusJob)job.Status);
            }

            return View(status);
        }

        // Delete Status
        public async Task<IActionResult> Delete_Status(int ID)
        {
            await DisplayDropdown();
            var status = await _statusRepository.GetByIdAsync(ID);
            var getjobname = await _jobRepository.GetByIdAsync(status.JobID);
            var companyname = _companyRepository.Details_CPN(getjobname.CompanyID).FirstOrDefault();

            ViewBag.CompanyName = companyname;
            ViewBag.Jobname = getjobname.Title;

            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }


        // Process delete status
        [HttpPost, ActionName("Delete_Status")]
        public async Task<IActionResult> DeleteConfirmed_Company(int id)
        {
            await _statusRepository.DeleteAsync(id);
            return RedirectToAction(nameof(StatusJob));

        }

		//***************************************************************************************
		//create applications
		public async Task<IActionResult> CreateApplication(int id)
		{
			await DisplayDropdown();
			var user = await _userManager.GetUserAsync(User);
			ViewBag.Email = user.Email;
			var status = await _statusRepository.GetAllAsync();

			var job = await _jobRepository.GetByIdAsync(id);
			ViewBag.GetJob = job;

			if (status == null)
			{
				return NotFound();
			}
			return View();
		}
		// add status job
		[HttpPost]
		public async Task<IActionResult> CreateApplication(Models.StatusJob statusJob, IFormFile imgCV, int id)
		{
			statusJob.ID = 0;
			statusJob.JobID = id;
			if (imgCV != null)
			{
				// save imgae
				statusJob.imgCV = await SaveImage(imgCV);
			}

			statusJob.Status = (int)Constants.StatusJob.Inprogress;
			statusJob.Read = (int)Constants.ViewStatus.NoRead;

			await _statusRepository.AddAsync(statusJob);
			return RedirectToAction(nameof(StatusJob));

		}

		//Luu anh
		private async Task<string> SaveImage(IFormFile image)
		{
			var savePath = Path.Combine("wwwroot/LayoutTimViec/img", image.FileName);
			using (var fileStream = new FileStream(savePath, FileMode.Create))
			{
				await image.CopyToAsync(fileStream);
			}
			return "LayoutTimViec/img/" + image.FileName;
		}

	}
}

TimViec/Views/Job/Details_Job.cshtml
@model List<TimViec.ViewModel.Details_Job>

@{
    ViewData["Title"] = "Ứng tuyển";
    Layout = "~/Views/Shared/_LayoutTimViec.cshtml";
}

<style>
    .form-container {
        margin-left: 400px;
        width: 800px;
        margin-top: 100px;
        border-radius: 10px;
        padding: 10px;
    }

</style>
<br />
<section class="explore-work" id="explore" style="background-color: #e2e2e2;margin-top: -20px;">
    <div class="container expanded">
        <div class="row" style="margin-top: 25px;">
            @foreach (var item in Model)
            {
                <div class="col-lg-4" style="width: 28%;background-color: white;border-radius: 10px;margin-left: 20px;padding: 10px;">
                    <div class="left-image">
                        <img style="width: 100%; height: auto" src="~/LayoutTimViec/img/@item.Logo" alt="Interior Design Work">
                    </div>
                    <hr style="border: solid 1px black" />
                    <div class="left" style="padding-left: 14px;">
                        <ul>
                            <li>
                                <h4>Rank</h4>
                                <ul class="info">
                                    <li>
                                        <span>
                                            • @item.rank
                                        </span>
                                    </li>
                                </ul>
                            </li>
                            <br />
                            <li>
                                <h4>Language</h4>
                                <ul class="info">
                                    <li>
                                        <span class="float-start">
                                            • @item.R1_Language
                                        </span>
                                    </li>
                                    <li>
                                        <span class="float-start">
                                            • @item.R2_Language
                                        </span>
                                    </li>
                                    <li>
                                        <span class="float-start">
                                            • @item.R3_Language
                                        </span>
                                    </li>
                                </ul>
                            </li>
                            <br />
                            <li>
                                <h4>Salary</h4>
                                <ul class="info">
                                    <li>
                                        <span>
                                            • @item.Salary
                                        </span>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <br />
                    <a class="badge badge-pill badge-danger" style="font-size: 25px; background-color: rgb(35 97 157); padding: 10px;width: 100%" asp-area="" asp-controller="StatusJob" asp-action="CreateApplication" asp-route-id="@item.Id">Apply now</a>

                </div>

                <div class="col-lg-8" style="background-color: white;border-radius: 10px;padding: 30px;margin-left: 20px;">
                    <h1 style="font-size: 30px">@item.Name</h1>
                    <hr />
                    <div class="right-content">
                        <ul>
                            <li>
                                <h4>• Reponsible</h4>
                                <ul class="info">
                                    <li>
                                        <p style="text-align: justify; white-space: pre-line">
                                            @item.work_responsitory
                                        </p>
                                    </li>
                                </ul>
                            </li>
                            <br />
                            <li>
                                <h4>• Treatment</h4>
                                <ul class="info">
                                    <li>
                                        <p style="text-align: justify;white-space: pre-line">
                                            @item.treatment
                                        </p>
                                    </li>
                                </ul>
                            </li>
                            <br />
                            <li>
                                <h4>• Your skills</h4>
                                <ul class="info">
                                    <li>
                                        <p style="text-align: justify;white-space: pre-line">
                                            @item.advanced_skill
                                        </p>
                                    </li>
                                </ul>
                            </li>
                            <br />                          
                        </ul>
                    </div>
                </div>
                <div class="col-lg-8" style="background-color: white;border-radius: 10px;padding: 30px;margin-right: 23px;margin-top: 10px;float: right">
                    <a asp-action="Details_CPN" asp-controller="Home" asp-route-id="@item.CompanyID"><h1 style="font-size: 36px">Company @item.CompanyName</h1></a>
                    <hr />
                    <div class="right-content">
                        <div style="display: flex; justify-content: space-evenly">
                            <div style="width: 130px">
                                <img style="margin-left: 40px; width: 50px" src="~/LayoutTimViec/logo/users.png" /><br /><h1 style="font-size:15px; text-align: center">Size</h1>
                                <span style="display: flex; justify-content: center">@item.size</span>
                            </div>
                            <div style="width: 130px">
                                <img style="margin-left: 40px; width: 50px" src="~/LayoutTimViec/logo/hotel.png" /><br /><h1 style="font-size:15px; text-align: center">Type</h1>
                                <span style="display: flex; justify-content: center">@item.type</span>
                            </div>
                            <div style="width: 130px">
                                <img style="margin-left: 40px; width: 50px" src="~/LayoutTimViec/logo/map-pin.png" /><br /><h1 style="font-size:15px; text-align: center">City</h1>
                                <span style="display: flex; justify-content: center">@item.city</span>
                            </div>
                        </div>
                        <ul>
                            <li>
                                <h4>Address</h4>
                                <ul class="info">
                                    <li>
                                        <p>
                                            • @item.Location
                                        </p>
                                    </li>
                                </ul>
                            </li>
                            <br />
                            <li>
                                <h4>Description</h4>
                                <ul class="info">
                                    <li>
                                        <p style="text-align: justify;">
                                            • @item.descriptioncpn
                                        </p>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            }
        </div>
    </div>
    <br />
</section>

TimViec/Views/Job/GetAllFavouriteJob.cshtml
@model IEnumerable<TimViec.Models.favourite_job>
@{
	ViewData["Title"] = "Job";
	Layout = "~/Views/Shared/_LayoutTimViec.cshtml";
}

<section id="explore" class="explore">
	<div class="container">
		<div class="section-header">
			<h2>Favorite job</h2>

		</div><!--/.section-header-->
		<div class="explore-content">
			<div class="row">

				@foreach (var item in Model)
				{
					<div class=" col-md-4 col-sm-6">
						<div class="single-explore-item">
							<div class="single-explore-img">
								<img style="height: 200px; width: 100%" src="~/LayoutTimViec/img/@item.image" alt="explore image">
								<div class="single-explore-img-info">
									<button onclick="window.location.href='#'" style="width: 35px;height: 37px;">
										<a asp-action="ChangeFavourite_Job" asp-route-id="@item.Id"><img src="~/LayoutTimViec/img/star.png" /></a>
									</button>
								</div>
							</div>
							<div class="single-explore-txt bg-theme-1">
								<h2><a style="white-space: nowrap;overflow: hidden; text-overflow: ellipsis; width: 307px" asp-action="Details_Job" asp-route-id="@item.IDJob">@item.Name</a></h2>
								<p class="explore-rating-price">
									<a href="#">@item.R1_Language</a>
									<span class="explore-price-box">@item.R2_Language</span>
									<a href="#">@item.R3_Language</a>
								</p>
								<hr />
								<div class="explore-open-close-part">
									<div class="row">
										<div class="col-sm-5">
											<button class="close-btn" onclick="window.location"><a asp-action="Details_Job" asp-route-id="@item.IDJob">Chi tiết</a></button>
										</div>
										<div class="col-sm-7">
											<div class="explore-map-icon">
												<a href="#"><i data-feather="map-pin"></i></a>
												<a href="#"><i data-feather="upload"></i></a>
												<a href="#"><i data-feather="heart"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				}
			</div>
		</div>
	</div><!--/.container-->
</section><!--/.explore-->
<!--explore end -->

TimViec/Views/Job/Job.cshtml
@model IEnumerable<TimViec.Models.Job>
@{
	ViewData["Title"] = "Job";
	Layout = "~/Views/Shared/_LayoutTimViec.cshtml";
}

<section id="explore" class="explore">
	<div class="container">
		<div class="section-header">
			<h2>List job</h2>
		</div><!--/.section-header-->
		<div class="explore-content">
			<div class="row">
				@foreach (var item in Model)
				{
					<div class=" col-md-4 col-sm-6">
						<div class="single-explore-item">
							<div class="single-explore-img">
								<img style="height: 200px; width: 100%" src="~/LayoutTimViec/img/@item.img" alt="explore image">
								<div class="single-explore-img-info">
									<button onclick="window.location.href='#'" style="width: 35px;height: 37px;">
										<a asp-action="Favourite_Job" asp-route-id="@item.Id"><img src="~/LayoutTimViec/img/star.png" /></a>
									</button>
								</div>
							</div>
							<div class="single-explore-txt bg-theme-1">
								<h2><a style="white-space: nowrap;overflow: hidden; text-overflow: ellipsis; width: 307px" asp-action="Details_Job" asp-route-id="@item.Id">@item.Title</a></h2>
								<p class="explore-rating-price">
									<a href="#">@item.R1_Language</a>
									<span class="explore-price-box">@item.R2_Language</span>
									<a href="#">@item.R3_Language</a>
								</p>
								<hr />
								<div class="explore-open-close-part">
									<div class="row">
										<div class="col-sm-5">
											<button class="close-btn" onclick="window.location"><a asp-action="Details_Job" asp-route-id="@item.Id">Chi tiết</a></button>
										</div>
										<div class="col-sm-7">
											<div class="explore-map-icon">
												<a href="#"><i data-feather="map-pin"></i></a>
												<a href="#"><i data-feather="upload"></i></a>
												<a href="#"><i data-feather="heart"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				}
			</div>
		</div>
	</div><!--/.container-->
</section><!--/.explore-->
<!--explore end -->